### ISSUE TITLE
Parsing errors - appears broken

### ISSUE THREAD

**Issue by jantman** [Jaymon/wishlist#7]
For at least a few weeks now, I seem to be getting errors trying to parse public wishlists:

```
[2017-10-11 06:45:29,648 ERROR] Exception updating project  with list https://www.amazon.com/gp/registry/wishlist/1KLDB4BQXRYFV
Traceback (most recent call last):
  File "/app/lib/python3.6/site-packages/biweeklybudget/wishlist2project.py", line 83, in run
    if self._do_project(list_url, proj):
  File "/app/lib/python3.6/site-packages/biweeklybudget/wishlist2project.py", line 103, in _do_project
    witems = self._wishlist_items(list_url)
  File "/app/lib/python3.6/site-packages/biweeklybudget/wishlist2project.py", line 170, in _wishlist_items
    if item.price > 0:
  File "/app/lib/python3.6/site-packages/wishlist/core.py", line 122, in price
    price_str = el.contents[0].strip()
TypeError: 'NoneType' object is not callable
```

I also found a previous issue where pagination was not working, but I worked around that.

I'll try opening a PR to fix these...

**Comment by jantman** [comment]
I've identified two current issues using one of my public wishlists as an example: https://www.amazon.com/gp/registry/wishlist/1KLDB4BQXRYFV

1. Wishlists are no longer paginated, but rather lazy-loaded via xmlhttprequest. As a result, ``get_total_pages_from_body()`` is broken.
2. The ``itemPrice_`` span now includes a number of child elements with the price broken out in different ways. That is breaking the ``price`` property of WishlistElement.

I'll have fixes for these in a PR shortly.

**Comment by jantman** [comment]
I've opened #8 to fix this.
